// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgDh_maVz1waStwqYKineGtWjpRUzPlbg',
    appId: '1:382841062479:web:0418a3410f351574b0563a',
    messagingSenderId: '382841062479',
    projectId: 'csmproject-520d3',
    authDomain: 'csmproject-520d3.firebaseapp.com',
    storageBucket: 'csmproject-520d3.firebasestorage.app',
    measurementId: 'G-77FBKF2CPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMKnGY7JXyiYUH4_k7Cp5hIH9qZLJaCjo',
    appId: '1:382841062479:android:1a525462e3941905b0563a',
    messagingSenderId: '382841062479',
    projectId: 'csmproject-520d3',
    storageBucket: 'csmproject-520d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABafcK-185Dqz-70_gTAbkiT9JsjgHrVg',
    appId: '1:382841062479:ios:a93486a63f84363cb0563a',
    messagingSenderId: '382841062479',
    projectId: 'csmproject-520d3',
    storageBucket: 'csmproject-520d3.firebasestorage.app',
    iosBundleId: 'com.example.orbitCsm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABafcK-185Dqz-70_gTAbkiT9JsjgHrVg',
    appId: '1:382841062479:ios:a93486a63f84363cb0563a',
    messagingSenderId: '382841062479',
    projectId: 'csmproject-520d3',
    storageBucket: 'csmproject-520d3.firebasestorage.app',
    iosBundleId: 'com.example.orbitCsm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgDh_maVz1waStwqYKineGtWjpRUzPlbg',
    appId: '1:382841062479:web:19e2b4a425d3c34cb0563a',
    messagingSenderId: '382841062479',
    projectId: 'csmproject-520d3',
    authDomain: 'csmproject-520d3.firebaseapp.com',
    storageBucket: 'csmproject-520d3.firebasestorage.app',
    measurementId: 'G-4WEG2GBWGC',
  );
}
